First commit
loranazarenko/OnlineBookStore pull request #18
Opened 2024-03-17 19:18 UTC by loranazarenko

2024-03-18 18:10 UTC, kerrrusha requested changes

2024-03-18 18:10 UTC, kerrrusha commented on src/main/java/mate/academy/onlinebookstore/controller/ShoppingCartController.java
> +        return shoppingCartService.getShoppingCart(pageable, authentication);
dont pass authentication to service, pass only userId

2024-03-18 18:10 UTC, kerrrusha commented on src/main/java/mate/academy/onlinebookstore/controller/ShoppingCartController.java
> +        return shoppingCartService.addBookToShoppingCart(cartItemRequestDto, authentication);
same

2024-03-18 18:10 UTC, kerrrusha commented on src/main/java/mate/academy/onlinebookstore/controller/ShoppingCartController.java
> +        return shoppingCartService.update(cartItemId, cartItemUpdateRequestDto, authentication);
same

2024-03-18 18:10 UTC, kerrrusha commented on src/main/java/mate/academy/onlinebookstore/controller/ShoppingCartController.java
> +        return shoppingCartService.deleteById(cartItemId, authentication);
same

2024-03-18 18:10 UTC, kerrrusha commented on src/main/java/mate/academy/onlinebookstore/entity/CartItem.java
> +@Data
dont use Data annotation on entities, as it cause bugs. replace it with getter/setter annotations instead

2024-03-18 18:10 UTC, kerrrusha commented on src/main/java/mate/academy/onlinebookstore/entity/ShoppingCart.java
> +@Data
same

2024-03-18 18:10 UTC, kerrrusha commented on src/main/java/mate/academy/onlinebookstore/entity/ShoppingCart.java
> +    @EqualsAndHashCode.Exclude
instead you can use EqualsAndHashCodeOf()...
```suggestion
@Table(name = "shopping_carts")
public class ShoppingCart {
    @Id
    private Long id;

    @MapsId
    @OneToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "id", nullable = false)
    private User user;
    
```

2024-03-18 18:10 UTC, kerrrusha commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                        cir -> cir.setQuantity(cir.getQuantity() + cartItemRequestDto.quantity()),
please obfuscate code like this var name

2024-03-19 12:42 UTC, artemZhuravskyi requested changes

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/entity/ShoppingCart.java
> +    private boolean isDeleted = false;
We separate fields with new lines, in case they serve different purposes. `id`, `user`, `cartItems`, and `isDeleted` are all table columns. So we don't need it here

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/controller/ShoppingCartController.java
> +    }
Private methods should be after public ones, according to convention.

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/controller/ShoppingCartController.java
> +    public ShoppingCartResponseDto update(@PathVariable
You have to be consistent with method naming, if you have `getShoppingCart` make `updateShoppingCart`

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/controller/ShoppingCartController.java
> +    public ShoppingCartResponseDto delete(@PathVariable Long cartItemId,
```suggestion
    public ShoppingCartResponseDto deleteShoppingCart(@PathVariable Long cartItemId,
```

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/entity/CartItem.java
> +
```suggestion
```

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/entity/CartItem.java
> +
```suggestion
```

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/entity/CartItem.java
> +
```suggestion
```

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/entity/CartItem.java
> +
```suggestion
```

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/repository/CartItemRepository.java
> +    Optional<CartItem> findByShoppingCartAndBookId(ShoppingCart shoppingCart, Long id);
```suggestion
    Optional<CartItem> findByShoppingCartAndBookId(ShoppingCart shoppingCart, Long bookId);
```

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/repository/ShoppingCartRepository.java
> +    ShoppingCart findByUserId(Long userId);
```suggestion
    Optional<ShoppingCart> findByUserId(Long userId);
```

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/ShoppingCartService.java
> +    ShoppingCartResponseDto deleteById(Long id,
again use consistent naming convention

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +@AllArgsConstructor
Imho RequieredArgsConstructor looks more flexible

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        }
redo using Optional<ShoppingCart>

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +            User userFromBase = userRepository.getReferenceById(userId);
What's the reason to use getReferenceById instead of findById?

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                        cir -> cir.setQuantity(cir.getQuantity() + cartItemRequestDto.quantity()),
```suggestion
                        cartItem -> cartItem.setQuantity(cir.getQuantity() + cartItemRequestDto.quantity()),
```

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    }
move private method after public ones

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart copyShoppingCart = shoppingCart;
```suggestion
        ShoppingCart shoppingCartCopy = shoppingCart;
```

2024-03-19 12:42 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
handle Optional

2024-03-19 20:33 UTC, loranazarenko commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +            User userFromBase = userRepository.getReferenceById(userId);
The main difference between these methods is that getReferenceById(ID) is lazy. Spring won’t send a database request until we explicitly try to use the entity within a transaction.

2024-03-20 12:45 UTC, artemZhuravskyi requested changes
Excellent work. It just needs some polish

2024-03-20 12:45 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/repository/CartItemRepository.java
> +    Optional<CartItem> findByShoppingCartAndBookId(ShoppingCart shoppingCart, Long id);
not fixed

2024-03-20 12:45 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                                                      Long userId) {
```suggestion
    public ShoppingCartResponseDto updateShoppingCart(Long id, ,Long userId
                                                      CartItemUpdateRequestDto cartItemUpdateRequestDto) {
```

2024-03-20 12:45 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                                              Long userId) {
```suggestion
    public ShoppingCartResponseDto deleteById(Long id, Long userId) {
```

2024-03-20 12:45 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                );
Move this logic to CartItemService

2024-03-20 12:45 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                        () -> new EntityNotFoundException("Can't find cart item with id " + id));
Move this logic to CartItemService

2024-03-20 12:45 UTC, artemZhuravskyi commented on src/main/java/mate/academy/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                        () -> new EntityNotFoundException("Can't find cart item with id " + id));
Move this logic to CartItemService

2024-03-21 17:29 UTC, Vasul-Pankiv approved these changes

2024-03-21 17:30 UTC, merged