First commit
loranazarenko/OnlineBookStore pull request #21
Opened 2024-07-04 03:26 UTC by loranazarenko

![Coverage](https://github.com/loranazarenko/OnlineBookStore/assets/5892607/f056267c-2cce-4c59-b806-5b94ba083440)

2024-07-04 07:44 UTC, Elena-Bruyako requested changes
Let' rename test methods, also add not valid cases

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/dto/BookDto.java
> +                      String isbn, java.math.BigDecimal price, String description,
```suggestion
                      String isbn, BigDecimal price, String description,
```

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/dto/CategoryRequestDto.java
>          @NotEmpty
```suggestion
        @NotBlank
```

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/dto/CreateBookRequestDto.java
> +        @NotNull
```suggestion
        @NotBlank
```

For all String types

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/entity/Book.java
>  @Where(clause = "is_deleted=false")
`@Where` is deprecated, use `@SQLRestriction` instead

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/main/java/mate/academy/onlinebookstore/entity/Category.java
>  @Where(clause = "is_deleted = FALSE")
the same
Check all entities

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/util/UtilsForTests.java
> +public class UtilsForTests {
```suggestion
public class TestUtils {
```

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +    void getBookById_checkValidId_returnOneBook() throws Exception {
```suggestion
    void getBookById_ValidId_Ok() throws Exception {
```

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +    void getBookById_checkInvalidId_returnOneBook() throws Exception {
```suggestion
    void getBookById_InvalidId_ShouldThrowException() throws Exception {
```

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +        ResultActions resultActions = mockMvc.perform(get("/books/{id}", invalidId)
Or you can 
```suggestion
        mockMvc.perform(get("/books/{id}", invalidId)
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isNotFound())
                .andExpect(result -> assertTrue(result.getResolvedException()
                        instanceof EntityNotFoundException))
                .andExpect(result -> assertEquals("Can't find book by id%s"
                        .formatted(9), result.getResolvedException().getMessage()));
```

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +    public void createBook_checkValidData_createOneBook() throws Exception {
```suggestion
    public void createBook_ValidRequestDto_Ok() throws Exception {
```

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +    void updateBook_checkValidId_updatedOneBook() throws Exception {
```suggestion
    void updateBook_ExistingBookWithValidRequestDto_Ok() throws Exception {
```

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +}
Add test to update not existing book

2024-07-04 07:44 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/service/BookServiceTest.java
> +
Add not valid cases

2024-07-09 06:57 UTC, sarakhmen approved these changes
good job! Let's also use more meaningful commit names next time ;)

2024-07-17 16:58 UTC, merged